/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MedgrupoPrivacyPolicy {
        "buttonText": string;
        "link": string;
        "linkText": string;
        "message": string;
    }
}
declare global {
    interface HTMLMedgrupoPrivacyPolicyElement extends Components.MedgrupoPrivacyPolicy, HTMLStencilElement {
    }
    var HTMLMedgrupoPrivacyPolicyElement: {
        prototype: HTMLMedgrupoPrivacyPolicyElement;
        new (): HTMLMedgrupoPrivacyPolicyElement;
    };
    interface HTMLElementTagNameMap {
        "medgrupo-privacy-policy": HTMLMedgrupoPrivacyPolicyElement;
    }
}
declare namespace LocalJSX {
    interface MedgrupoPrivacyPolicy {
        "buttonText"?: string;
        "link"?: string;
        "linkText"?: string;
        "message"?: string;
    }
    interface IntrinsicElements {
        "medgrupo-privacy-policy": MedgrupoPrivacyPolicy;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "medgrupo-privacy-policy": LocalJSX.MedgrupoPrivacyPolicy & JSXBase.HTMLAttributes<HTMLMedgrupoPrivacyPolicyElement>;
        }
    }
}
